In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_classification
from sklearn.svm import OneClassSVM
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

import math
from math import sqrt
from sklearn.metrics import mean_absolute_error as mae
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import r2_score

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from matplotlib.pylab import rcParams
import matplotlib.gridspec as gridspec
from scipy.stats import zscore
import csv
import codecs
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
%config InlineBackend.figure_format = 'retina'

In [2]:
data = []

with codecs.open('dataset/good.csv', encoding='utf-8', errors='ignore') as csvfile:
    rows = csv.reader(csvfile)
    for row in rows:
        data.append(row)
        
data1 = pd.DataFrame(data)
data1.shape

(4559, 99)

In [3]:
data = []

with codecs.open('dataset/bad.csv', encoding='utf-8', errors='ignore') as csvfile:
    rows = csv.reader(csvfile)
    for row in rows:
        data.append(row)
        
data2 = pd.DataFrame(data)
data2.shape

(135, 99)

In [12]:
data = []

with codecs.open('dataset/val.csv', encoding='utf-8', errors='ignore') as csvfile:
    rows = csv.reader(csvfile)
    for row in rows:
        data.append(row)
        
data3 = pd.DataFrame(data)
data3.shape

(1815, 99)

In [5]:
# 留下的特徵
all_name = [
#     'ShotSN',
#     'MoldClampedTime',
#     'MoldReleasedTime',
#     'MOID',
#     'ProdID',
    'Sensor2_MaxPressure',
    'Sensor2_SumStage1Pressure',
#     'Sensor2_MaxPressureTime',
    'Sensor2_AvgStage1PressureSlope',
    'Sensor2_AvgStage2PressureSlope',
    'Sensor2_MoldReleasePressure',
    'Sensor3_MaxPressure',
    'Sensor3_SumStage1Pressure',
#     'Sensor3_MaxPressureTime',
    'Sensor3_AvgStage1PressureSlope',
    'Sensor3_AvgStage2PressureSlope',
    'Sensor3_MoldReleasePressure',
    'Sensor4_MaxPressure',
    'Sensor4_SumStage1Pressure',
#     'Sensor4_MaxPressureTime',
    'Sensor4_AvgStage1PressureSlope',
    'Sensor4_AvgStage2PressureSlope',
    'Sensor4_MoldReleasePressure',
    'Sensor5_StartTemperature',
    'Sensor5_MaxTemperature',
    'Sensor5_AvgStage2TemperatureSlope',
    'Sensor5_MoldReleaseTemperature',
#     'Sensor1_Stage1StartTime',
#     'Sensor1_Stage1EndTime',
#     'Sensor1_Stage1Period',
    'Sensor1_AvgStage1PressureSlope',
    'Sensor1_SumStage1Pressure',
    'Sensor1_Stage1EndPressure',
#     'Sensor1_Stage2StartTime',
#     'Sensor1_Stage2EndTime',
#     'Sensor1_Stage2Period',
    'Sensor1_AvgStage2PressureSlope',
    'Sensor1_SumStage2Pressure',
#     'Sensor1_Stage3StartTime',
#     'Sensor1_Stage3EndTime',
#     'Sensor1_Stage3Period',
    'Sensor1_MaxStage3Pressure',
#     'Sensor1_MaxStage3PressureTime',
    'Sensor1_SumStage3Pressure',
#     'Sensor1_CycleTime',
    'Sensor1_SumPressure',
#     'Soft_MoldClampedCycleTime',
#     'Soft_MoldBasedCycleTime',
    'Soft_MoldShotInterval',
#     'Soft_MoldCompleteCycleTime',
    'Soft_DiffMaxPressure',
#     'Soft_DiffIncreasePressureTime',
    'Soft_DiffMoldReleasePressure',
    'Type',
]

In [6]:
data1.columns = data1.iloc[0]
data1 = data1.iloc[2:, :]
data1 = data1.reset_index(drop=True)
data1.head()

0 ShotSN MoldClampedTime MoldReleasedTime MOID    ProdID Sensor2_MaxPressure  \
0      1         09:23.8          11:49.8  t11  #2-4^TOY                1.06   
1      2         12:12.2          14:38.1  t11  #2-4^TOY                0.96   
2      3         15:00.4          17:26.5  t11  #2-4^TOY                0.98   
3      4         17:48.9          20:14.9  t11  #2-4^TOY                1.09   
4      5         20:37.5          23:03.5  t11  #2-4^TOY                   1   

0 Sensor2_SumStage1Pressure Sensor2_MaxPressureTime  \
0                  14.14879               48.305779   
1                  8.488392               46.251426   
2                 16.411448               53.499554   
3                 10.686955               43.714665   
4                 13.724422               50.387868   

0 Sensor2_AvgStage1PressureSlope Sensor2_AvgStage2PressureSlope  \
0                       0.021944                      -0.011339   
1                       0.020756                      -0.010049   
2                       0.018318                      -0.011088   
3                       0.024935                      -0.010695   
4                       0.018457                       -0.01094   

0 Sensor2_MoldReleasePressure Sensor3_MaxPressure Sensor3_SumStage1Pressure  \
0                           0                0.99                  9.154309   
1                           0                1.12                 10.489044   
2                           0                1.02                  7.885406   
3                        0.04                1.03                  7.681343   
4                           0                1.08                    9.1746   

0 Sensor3_MaxPressureTime Sensor3_AvgStage1PressureSlope  \
0               45.064541                       0.021747   
1               43.460442                       0.025541   
2               44.623369                       0.020841   
3               42.801217                       0.023598   
4               43.790583                       0.024435   

0 Sensor3_AvgStage2PressureSlope Sensor3_MoldReleasePressure  \
0                      -0.010132                        0.01   
1                      -0.010781                        0.06   
2                      -0.010282                        0.02   
3                      -0.010294                        0.01   
4                      -0.010612                        0.04   

0 Sensor4_MaxPressure Sensor4_SumStage1Pressure Sensor4_MaxPressureTime  \
0                1.04                   7.08935               42.935417   
1                0.99                 10.312204                46.70804   
2                1.09                 11.335504               46.196566   
3                1.02                 11.518071               48.078887   
4                1.09                  8.964627               43.536887   

0 Sensor4_AvgStage1PressureSlope Sensor4_AvgStage2PressureSlope  \
0                       0.024223                      -0.010319   
1                       0.021196                      -0.010413   
2                       0.023595                      -0.011182   
3                       0.020175                      -0.010873   
4                       0.025036                      -0.010788   

0 Sensor4_MoldReleasePressure Sensor5_StartTemperature Sensor5_MaxTemperature  \
0                        0.02                     0.48                   1.98   
1                           0                     0.54                   1.98   
2                        0.02                     0.43                   1.98   
3                           0                     0.27                   1.98   
4                        0.03                     0.48                   1.98   

0 Sensor5_AvgStage2TemperatureSlope Sensor5_MoldReleaseTemperature  \
0                         -0.010371                            0.7   
1                         -0.010136                           0.73   
2            

In [7]:
data2.columns = data2.iloc[0]
data2 = data2.iloc[2:, :]
data2 = data2.reset_index(drop=True)
data2.head()

0 ShotSN MoldClampedTime MoldReleasedTime MOID    ProdID Sensor2_MaxPressure  \
0   2254         10:29.6          12:54.0  t11  #2-4^TOY                0.05   
1   2255         13:16.0          15:40.4  t11  #2-4^TOY                0.11   
2   2256         16:02.5          18:26.4  t11  #2-4^TOY                0.05   
3   2257         18:48.8          21:13.2  t11  #2-4^TOY                0.14   
4   2258         21:35.1          23:59.5  t11  #2-4^TOY                0.06   

0 Sensor2_SumStage1Pressure Sensor2_MaxPressureTime  \
0                  0.066954               30.226254   
1                  1.101516               27.546706   
2                  0.544567               57.047626   
3                  2.031487               35.601051   
4                         0                 0.00042   

0 Sensor2_AvgStage1PressureSlope Sensor2_AvgStage2PressureSlope  \
0                       0.001323                      -0.000456   
1                       0.003993                      -0.000979   
2                       0.000701                      -0.000603   
3                       0.003933                      -0.000959   
4                              0                      -0.000429   

0 Sensor2_MoldReleasePressure Sensor3_MaxPressure Sensor3_SumStage1Pressure  \
0                           0                0.14                         0   
1                           0                0.03                   0.49645   
2                           0                0.03                  0.332434   
3                        0.04                0.02                  0.603321   
4                           0                0.18                  4.528611   

0 Sensor3_MaxPressureTime Sensor3_AvgStage1PressureSlope  \
0                0.000345                              0   
1               44.776663                       0.000447   
2               30.836741                       0.000324   
3               60.307064                       0.000166   
4               32.960578                       0.005158   

0 Sensor3_AvgStage2PressureSlope Sensor3_MoldReleasePressure  \
0                      -0.000858                        0.02   
1                      -0.000105                        0.02   
2                      -9.20E-05                        0.02   
3                      -0.000126                        0.01   
4                      -0.000935                        0.08   

0 Sensor4_MaxPressure Sensor4_SumStage1Pressure Sensor4_MaxPressureTime  \
0                 0.1                  1.218391               34.640692   
1                0.03                         0                0.000369   
2                0.19                  3.990315               29.822788   
3                0.13                         0                0.000366   
4                0.03                         0                 0.00042   

0 Sensor4_AvgStage1PressureSlope Sensor4_AvgStage2PressureSlope  \
0                       0.002887                       -0.00095   
1                              0                      -0.000214   
2                       0.006371                      -0.001453   
3                              0                      -0.000858   
4                              0                      -0.000214   

0 Sensor4_MoldReleasePressure Sensor5_StartTemperature Sensor5_MaxTemperature  \
0                           0                     0.14                   1.93   
1                           0                     0.52                   2.02   
2                        0.03                     0.32                   2.02   
3                        0.01                     0.29                   1.99   
4                           0                     0.44                   2.01   

0 Sensor5_AvgStage2TemperatureSlope Sensor5_MoldReleaseTemperature  \
0                         -0.010172                           0.67   
1                         -0.010048                           0.77   
2            

In [13]:
data3.columns = data3.iloc[0]
data3 = data3.iloc[2:, :]
data3 = data3.reset_index(drop=True)
data3.head()

0 ShotSN MoldClampedTime MoldReleasedTime MOID    ProdID Sensor2_MaxPressure  \
0      1         26:57.0          29:21.9  t13  #2-4^TOY                1.12   
1      2         29:44.9          32:10.0  t13  #2-4^TOY                1.13   
2      3         32:33.3                   t13  #2-4^TOY                       
3      4         43:43.9          46:09.0  t13  #2-4^TOY                1.13   
4      5         46:31.8          48:56.8  t13  #2-4^TOY                1.12   

0 Sensor2_SumStage1Pressure Sensor2_MaxPressureTime  \
0                 20.037444               41.466042   
1                   8.56581               30.725737   
2                                                     
3                  8.963635               31.499059   
4                  9.770712               32.114165   

0 Sensor2_AvgStage1PressureSlope Sensor2_AvgStage2PressureSlope  \
0                        0.02701                      -0.011282   
1                       0.036777                      -0.010257   
2                                                                 
3                       0.035557                      -0.010249   
4                       0.034565                      -0.010204   

0 Sensor2_MoldReleasePressure Sensor3_MaxPressure Sensor3_SumStage1Pressure  \
0                           0                 1.1                 15.418197   
1                           0                1.21                 14.582229   
2                                                                             
3                        0.01                1.16                  9.730695   
4                        0.01                1.24                 12.882139   

0 Sensor3_MaxPressureTime Sensor3_AvgStage1PressureSlope  \
0               37.871087                       0.028518   
1               35.385415                       0.033913   
2                                                          
3                31.80324                        0.03616   
4               32.824572                       0.037472   

0 Sensor3_AvgStage2PressureSlope Sensor3_MoldReleasePressure  \
0                      -0.010596                        0.01   
1                      -0.011184                        0.03   
2                                                              
3                      -0.010462                        0.02   
4                      -0.011289                        0.02   

0 Sensor4_MaxPressure Sensor4_SumStage1Pressure Sensor4_MaxPressureTime  \
0                1.16                  7.664932               29.966163   
1                1.15                  8.713303               31.384421   
2                                                                         
3                1.16                  7.537426               29.876897   
4                1.12                  9.280557                32.21567   

0 Sensor4_AvgStage1PressureSlope Sensor4_AvgStage2PressureSlope  \
0                       0.038711                      -0.010472   
1                       0.036643                      -0.010501   
2                                                                 
3                       0.038826                       -0.01037   
4                       0.034456                      -0.010306   

0 Sensor4_MoldReleasePressure Sensor5_StartTemperature Sensor5_MaxTemperature  \
0                           0                     0.23                   2.01   
1                           0                     0.35                      2   
2                                                                               
3                        0.01                      0.1                   1.99   
4                           0                     0.01                   1.99   

0 Sensor5_AvgStage2TemperatureSlope Sensor5_MoldReleaseTemperature  \
0                         -0.014993                            0.1   
1                         -0.011856                           0.49   
2            

In [9]:
data_all = pd.concat([data1, data2])
data_all.shape

(4690, 99)

In [68]:
df = data_all[all_name]
df.shape

(4690, 31)

In [69]:
df_val = data3[all_name]
df_val.shape

(1813, 31)

In [70]:
df = df.apply(pd.to_numeric, errors='coerce')

In [71]:
df_val = df_val.apply(pd.to_numeric, errors='coerce')

In [72]:
df_nona = df.dropna()
df_nona_val = df_val.dropna()
df_nona.shape, df_nona_val.shape

((4655, 31), (1811, 31))

In [73]:
df_nona = df_nona.reset_index(drop=True)
df_nona_val = df_nona_val.reset_index(drop=True)
df_nona.head()

0  Sensor2_MaxPressure  Sensor2_SumStage1Pressure  \
0                 1.06                  14.148790   
1                 0.96                   8.488392   
2                 0.98                  16.411448   
3                 1.09                  10.686955   
4                 1.00                  13.724422   

0  Sensor2_AvgStage1PressureSlope  Sensor2_AvgStage2PressureSlope  \
0                        0.021944                       -0.011339   
1                        0.020756                       -0.010049   
2                        0.018318                       -0.011088   
3                        0.024935                       -0.010695   
4                        0.018457                       -0.010940   

0  Sensor2_MoldReleasePressure  Sensor3_MaxPressure  \
0                         0.00                 0.99   
1                         0.00                 1.12   
2                         0.00                 1.02   
3                         0.04                 1.03   
4                         0.00                 1.08   

0  Sensor3_SumStage1Pressure  Sensor3_AvgStage1PressureSlope  \
0                   9.154309                        0.021747   
1                  10.489044                        0.025541   
2                   7.885406                        0.020841   
3                   7.681343                        0.023598   
4                   9.174600                        0.024435   

0  Sensor3_AvgStage2PressureSlope  Sensor3_MoldReleasePressure  \
0                       -0.010132                         0.01   
1                       -0.010781                         0.06   
2                       -0.010282                         0.02   
3                       -0.010294                         0.01   
4                       -0.010612                         0.04   

0  Sensor4_MaxPressure  Sensor4_SumStage1Pressure  \
0                 1.04                   7.089350   
1                 0.99                  10.312204   
2                 1.09                  11.335504   
3                 1.02                  11.518071   
4                 1.09                   8.964627   

0  Sensor4_AvgStage1PressureSlope  Sensor4_AvgStage2PressureSlope  \
0                        0.024223                       -0.010319   
1                        0.021196                       -0.010413   
2                        0.023595                       -0.011182   
3                        0.020175                       -0.010873   
4                        0.025036                       -0.010788   

0  Sensor4_MoldReleasePressure  Sensor5_StartTemperature  \
0                         0.02                      0.48   
1                         0.00                      0.54   
2                         0.02                      0.43   
3                         0.00                      0.27   
4                         0.03                      0.48   

0  Sensor5_MaxTemperature  Sensor5_AvgStage2TemperatureSlope  \
0                    1.98                          -0.010371   
1                    1.98                          -0.010136   
2                    1.98                          -0.013864   
3                    1.98                          -0.012057   
4                    1.98                          -0.010695   

0  Sensor5_MoldReleaseTemperature  Sensor1_AvgStage1PressureSlope  \
0                            0.70                        0.034745   
1                            0.73                        0.030567   
2                            0.27                        0.030523   
3                            0.49                        0.036441   
4                            0.66                        0.035590   

0  Sensor1_SumStage1Pressure  Sensor1_Stage1EndPressure  \
0                     562.98                       1.44   
1                     644.65                       1.43   
2                     650.36                       1.43   
3                     

In [74]:
X = df_nona.iloc[:, :-1]
y = df_nona['Type']
X.shape, y.shape

((4655, 30), (4655,))

In [76]:
X1 = df_nona_val.iloc[:, :-1]
y1 = df_nona_val['Type']
X1.shape, y1.shape

((1811, 30), (1811,))

In [78]:
y.unique()

array([0, 1])

In [79]:
y[y==1] = -1  # 将异常点标记为-1
y[y==0] = 1   # 将正常点标记为1

In [81]:
y1[y1==0] = 1   # 将正常点标记为1

In [83]:
y.unique()

array([ 1, -1])

In [82]:
y1.unique()

array([1])

In [24]:
y.tail()

4650   -1
4651   -1
4652   -1
4653   -1
4654   -1
Name: Type, dtype: int64

In [84]:
scaler = StandardScaler()

In [26]:
# X = scaler.fit_transform(X)

In [37]:
# X1 = scaler.transform(X1)

In [85]:
# 划分数据集为训练集和测试集
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [86]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape, X1.shape, y1.shape

((3258, 30), (1397, 30), (3258,), (1397,), (1811, 30), (1811,))

In [87]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_val = scaler.transform(X1)

In [88]:
X_positive = X_train[y_train == 1]

In [89]:
X_positive.shape

(3177, 30)

In [90]:
clf = IsolationForest(n_estimators=85, contamination=0.04, random_state=42)

In [91]:
clf.fit(X_positive)

IsolationForest(behaviour='deprecated', bootstrap=False, contamination=0.04,
                max_features=1.0, max_samples='auto', n_estimators=85,
                n_jobs=None, random_state=42, verbose=0, warm_start=False)

In [92]:
y_pred = clf.predict(X_test)

In [93]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.3f}")

Accuracy: 0.946


In [96]:
confusion_matrix(y_test, y_pred)

array([[  20,   12],
       [  64, 1301]])

In [94]:
y_pred_val = clf.predict(X_val)

In [95]:
accuracy = accuracy_score(y1, y_pred_val)
print(f"Accuracy: {accuracy:.3f}")

Accuracy: 0.866


In [97]:
confusion_matrix(y1, y_pred_val)

array([[   0,    0],
       [ 243, 1568]])

In [130]:
# X[y == 1].shape

(4542, 30)

In [232]:
# from sklearn.ensemble import IsolationForest
# from sklearn.model_selection import cross_val_score

# # 将所有标签为 1 的样本视为正样本
# X = df_nona.iloc[:, :-1]
# y = df_nona['Type']

# y[y==1] = -1  # 将异常点标记为-1
# y[y==0] = 1   # 将正常点标记为1

# scaler = StandardScaler()
# X = scaler.fit_transform(X)

# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# X_positive = X_train[y_train == 1]

# # param_grid = {'n_estimators': [10, 50, 100, 500]}

# clf = IsolationForest(n_estimators=500, random_state=42)

# # cv_results = cross_val_score(clf, X_positive, cv=5, scoring='accuracy', fit_params=param_grid)

# # print("Best n_estimators:", param_grid['n_estimators'][cv_results.argmax()])

# clf.fit(X_positive)

# y_pred = clf.predict(X_test)

# accuracy = accuracy_score(y_test, y_pred)

# print(f"Accuracy: {accuracy:.3f}")

Accuracy: 0.940


In [233]:
# confusion_matrix(y_test, y_pred)

array([[ 13,  10],
       [ 46, 862]])

# 不同的算法
# 目前KO榜TOP 1為田弘光(誤)IsolationForest,其次為OneSVM
# 以這兩種下去調整參數

# 1. One SVM算法

In [34]:
# 创建One-Class SVM模型并拟合训练数据
ocsvm = OneClassSVM(kernel='rbf', nu=0.1)
ocsvm.fit(X_train)

# 使用测试集评估模型性能
y_pred = ocsvm.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, pos_label=-1)
recall = recall_score(y_test, y_pred, pos_label=-1)
f1 = f1_score(y_test, y_pred, pos_label=-1)

print(f"Accuracy: {accuracy:.3f}")
print(f"Precision: {precision:.3f}")
print(f"Recall: {recall:.3f}")
print(f"F1: {f1:.3f}")
print(f'MAE: {mae(y_test, y_pred)}')
print(f'MSE: {mse(y_test, y_pred)}')
print(f'RMSE: {sqrt(mse(y_test, y_pred))}')
print(f'R2: {r2_score(y_test, y_pred)}')


Accuracy: 0.918
Precision: 0.216
Recall: 0.731
F1: 0.333
MAE: 0.16326530612244897
MSE: 0.32653061224489793
RMSE: 0.5714285714285714
R2: -2.0070548236294097


In [35]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[ 19,   7],
       [ 69, 836]])

In [21]:
'''
            预测为正类   预测为负类
实际为正类       TP        FN
实际为负类       FP        TN

'''

# 2. DeepOCC算法 (無法判斷出不良品)

In [75]:
# 将数据转换为PyTorch张量
X_train_tensor = torch.Tensor(X_train)
y_train_tensor = torch.Tensor(y_train.to_numpy())
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

In [76]:
# 定义DeepOCC模型
class DeepOCC(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(DeepOCC, self).__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, output_dim)
        self.relu = nn.ReLU()
        
    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        out = self.relu(out)
        return out

In [80]:
# 定义DeepOCC模型的参数
input_dim = 30
hidden_dim = 10
output_dim = 1

# 初始化DeepOCC模型
deep_occ = DeepOCC(input_dim, hidden_dim, output_dim)

# 定义损失函数和优化器
criterion = nn.MSELoss()
optimizer = optim.Adam(deep_occ.parameters(), lr=0.01)

# 训练DeepOCC模型
for epoch in range(50):
    for x, y in train_loader:
        optimizer.zero_grad()
        output = deep_occ(x)
        loss = criterion(output, torch.ones(output.shape))
        loss.backward()
        optimizer.step()

# 对测试集进行分类
X_test_tensor = torch.Tensor(X_test)
test_dataset = TensorDataset(X_test_tensor)
test_loader = DataLoader(test_dataset, batch_size=32)
y_pred = []
for x in test_loader:
    output = deep_occ(x[0])
    y_pred.extend(output.detach().numpy())

# 将预测结果转换为二元分类结果
y_pred = [1 if x > 0.5 else -1 for x in y_pred]

# 计算模型的准确率
accuracy = sum([1 if x == y else -1 for x, y in zip(y_test, y_pred)]) / len(y_test)
precision = precision_score(y_test, y_pred, pos_label=-1)
recall = recall_score(y_test, y_pred, pos_label=-1)
f1 = f1_score(y_test, y_pred, pos_label=-1)

print(f"Accuracy: {accuracy:.3f}")
print(f"Precision: {precision:.3f}")
print(f"Recall: {recall:.3f}")
print(f"F1: {f1:.3f}")
print(f'MAE: {mae(y_test, y_pred)}')
print(f'MSE: {mse(y_test, y_pred)}')
print(f'RMSE: {sqrt(mse(y_test, y_pred))}')
print(f'R2: {r2_score(y_test, y_pred)}')

Accuracy: 0.942
Precision: 0.000
Recall: 0.000
F1: 0.000
MAE: 0.05800214822771214
MSE: 0.11600429645542427
RMSE: 0.3405940346738684
R2: -0.06829579260518504


In [81]:
confusion_matrix(y_test, y_pred)

array([[  0,  26],
       [  1, 904]])

# 3. IsolationForest算法

In [49]:
from sklearn.ensemble import IsolationForest

# 将所有标签为 1 的样本视为正样本
X_positive = X_train[y_train == 1]

# X = scaler.fit_transform(X_positive)

clf = IsolationForest(n_estimators=85, contamination=0.04, random_state=42)

clf.fit(X_positive)

y_pred = clf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print(f"Accuracy: {accuracy:.3f}")

ValueError: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required.

In [31]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[  20,   12],
       [  64, 1301]])

In [38]:
y_pred_val = clf.predict(X1)

accuracy_val = accuracy_score(y1, y_pred_val)

print(f"Accuracy: {accuracy_val:.3f}")

Accuracy: 0.000


In [39]:
confusion_matrix(y1, y_pred_val)

array([[   0,    0],
       [1811,    0]])

In [317]:
# 原結果
# Accuracy: 0.951
# Precision: 0.308
# Recall: 0.615
# F1: 0.410
# MAE: 0.09881847475832438
# MSE: 0.19763694951664876
# RMSE: 0.44456377440885664
# R2: -0.8200594985125376
# array([[ 16,  10],
#        [ 36, 869]])

In [25]:
# 计算混淆矩阵
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()

# 输出评估指标
accuracy = (tp + tn) / (tp + tn + fp + fn)
precision = tp / (tp + fp)
recall = tp / (tp + fn)
f1_score = 2 * precision * recall / (precision + recall)

print('Accuracy:', accuracy)
print('Precision:', precision)
print('Recall:', recall)
print('F1 Score:', f1_score)
print(f'R2: {r2_score(y_test, y_pred)}')

Accuracy: 0.945597709377237
Precision: 0.9908606245239908
Recall: 0.9531135531135531
F1 Score: 0.9716206123973113
R2: -1.430677655677656


# 4. Autoencoder算法

In [19]:
import numpy as np
from tensorflow import keras
from sklearn.datasets import make_classification

# 将所有标签为 1 的样本视为正样本
X_positive = X_train[y_train == 1]

# 定义 Autoencoder 模型
input_shape = (X_positive.shape[1],)
model = keras.Sequential([
    keras.layers.Dense(32, activation='relu', input_shape=input_shape),
    keras.layers.Dense(16, activation='relu'),
    keras.layers.Dense(8, activation='relu'),
    keras.layers.Dense(16, activation='relu'),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(input_shape[0], activation='linear')
])

# 编译模型
model.compile(optimizer='adam', loss='mse')

# 使用 Autoencoder 进行拟合
model.fit(X_positive, X_positive, epochs=100, batch_size=8)

# 預測模型
y_pred = model.predict(X_test)

# 计算重构误差
reconstruction_errors = np.mean(np.square(X_test - y_pred), axis=1)

# 定义阈值，将重构误差小于阈值的样本视为正常样本，大于阈值的样本视为异常样本
threshold = 0.1
y_pred = np.where(reconstruction_errors < threshold, 1, -1)

# 打印预测结果
# print(y_pred)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, pos_label=-1)
recall = recall_score(y_test, y_pred, pos_label=-1)
f1 = f1_score(y_test, y_pred, pos_label=-1)

print(f"Accuracy: {accuracy:.3f}")
print(f"Precision: {precision:.3f}")
print(f"Recall: {recall:.3f}")
print(f"F1: {f1:.3f}")
print(f'MAE: {mae(y_test, y_pred)}')
print(f'MSE: {mse(y_test, y_pred)}')
print(f'RMSE: {sqrt(mse(y_test, y_pred))}')
print(f'R2: {r2_score(y_test, y_pred)}')

2023-05-03 10:18:13.993725: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-03 10:18:15.918240: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 10041 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1080 Ti, pci bus id: 0000:06:00.0, compute capability: 6.1


Epoch 1/100
398/398 [==============================] - 1s 2ms/step - loss: 0.7864
Epoch 2/100
398/398 [==============================] - 1s 2ms/step - loss: 0.5873
Epoch 3/100
398/398 [==============================] - 1s 2ms/step - loss: 0.5124
Epoch 4/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4610
Epoch 5/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4265
Epoch 6/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4025
Epoch 7/100
398/398 [==============================] - 1s 2ms/step - loss: 0.3819
Epoch 8/100
398/398 [==============================] - 1s 2ms/step - loss: 0.3629
Epoch 9/100
398/398 [==============================] - 1s 2ms/step - loss: 0.3342
Epoch 10/100
398/398 [==============================] - 1s 2ms/step - loss: 0.3214
Epoch 11/100
398/398 [==============================] - 1s 2ms/step - loss: 0.3086
Epoch 12/100
398/398 [==============================] - 1s 2ms/step - loss: 0.2928
Epoch 13/100


In [104]:
import numpy as np
from tensorflow import keras
from sklearn.datasets import make_classification

# 将所有标签为 1 的样本视为正样本
X_positive = X[y == 1]

# 定义 Autoencoder 模型
input_shape = (X_positive.shape[1],)
model = keras.Sequential([
    keras.layers.Dense(32, activation='relu', input_shape=input_shape),
    keras.layers.Dense(16, activation='relu'),
    keras.layers.Dense(8, activation='relu'),
    keras.layers.Dense(16, activation='relu'),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(input_shape[0], activation='linear')
])

# 编译模型
model.compile(optimizer='adam', loss='mse')

# 使用 Autoencoder 进行拟合
model.fit(X_positive, X_positive, epochs=100, batch_size=8)

# 預測模型
y_pred = model.predict(X_test)

# 计算重构误差
reconstruction_errors = np.mean(np.square(X_test - y_pred), axis=1)

# 定义阈值，将重构误差小于阈值的样本视为正常样本，大于阈值的样本视为异常样本
threshold = 0.1
y_pred = np.where(reconstruction_errors < threshold, 1, -1)

# 打印预测结果
# print(y_pred)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, pos_label=-1)
recall = recall_score(y_test, y_pred, pos_label=-1)
f1 = f1_score(y_test, y_pred, pos_label=-1)

print(f"Accuracy: {accuracy:.3f}")
print(f"Precision: {precision:.3f}")
print(f"Recall: {recall:.3f}")
print(f"F1: {f1:.3f}")
print(f'MAE: {mae(y_test, y_pred)}')
print(f'MSE: {mse(y_test, y_pred)}')
print(f'RMSE: {sqrt(mse(y_test, y_pred))}')
print(f'R2: {r2_score(y_test, y_pred)}')

Epoch 1/100
568/568 [==============================] - 1s 2ms/step - loss: 0.7558
Epoch 2/100
568/568 [==============================] - 1s 2ms/step - loss: 0.5442
Epoch 3/100
568/568 [==============================] - 1s 2ms/step - loss: 0.4795
Epoch 4/100
568/568 [==============================] - 1s 2ms/step - loss: 0.4284
Epoch 5/100
568/568 [==============================] - 1s 2ms/step - loss: 0.3919
Epoch 6/100
568/568 [==============================] - 1s 2ms/step - loss: 0.3723
Epoch 7/100
568/568 [==============================] - 1s 2ms/step - loss: 0.3525
Epoch 8/100
568/568 [==============================] - 1s 2ms/step - loss: 0.3294
Epoch 9/100
568/568 [==============================] - 1s 2ms/step - loss: 0.3157
Epoch 10/100
568/568 [==============================] - 1s 2ms/step - loss: 0.3026
Epoch 11/100
568/568 [==============================] - 1s 2ms/step - loss: 0.2974
Epoch 12/100
568/568 [==============================] - 1s 2ms/step - loss: 0.2873
Epoch 13/100


In [105]:
confusion_matrix(y_test, y_pred)

array([[ 26,   0],
       [108, 797]])

# 5. Deep Support Vector Data Description算法 (無法判斷不良品)

In [20]:
import numpy as np
from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
from keras import regularizers
from tensorflow.keras.optimizers import Adam
from keras.utils.vis_utils import plot_model
from sklearn.metrics import confusion_matrix, classification_report

# # 将所有标签为 1 的样本视为正样本
# X_positive = X[y == 1]

# # 对正样本进行标准化处理
# scaler = StandardScaler()
# X_positive = scaler.fit_transform(X_positive)

# 划分训练集和测试集
# X_train, X_test = train_test_split(X_positive, test_size=0.2, random_state=42)

# 定义 Deep SVDD 模型
input_shape = (X_positive.shape[1],)
model = Sequential([
    Dense(64, activation='relu', input_shape=input_shape, kernel_regularizer=regularizers.l2(0.01)),
    Dense(32, activation='relu', kernel_regularizer=regularizers.l2(0.01)),
    Dense(16, activation='relu', kernel_regularizer=regularizers.l2(0.01)),
    Dense(1, activation='sigmoid')
])

# 编译模型
model.compile(optimizer=Adam(learning_rate=0.001), loss='binary_crossentropy')

# 使用 Deep SVDD 进行拟合
model.fit(X_train, np.ones(X_train.shape[0]), epochs=50, batch_size=32, verbose=0)

# 对测试集进行预测，并计算性能指标
y_pred = model.predict(X_test)
y_pred = np.where(y_pred > 0.5, 1, -1)

cm = confusion_matrix(np.ones(X_test.shape[0]), y_pred)
print('Confusion matrix:\n', cm)

report = classification_report(np.ones(X_test.shape[0]), y_pred)
print('Classification report:\n', report)


Confusion matrix:
 [[1397]]
Classification report:
               precision    recall  f1-score   support

         1.0       1.00      1.00      1.00      1397

    accuracy                           1.00      1397
   macro avg       1.00      1.00      1.00      1397
weighted avg       1.00      1.00      1.00      1397



In [21]:
confusion_matrix(y_test, y_pred)

array([[   0,   32],
       [   0, 1365]])

In [98]:
# list(zip(y_test, y_pred))